CREATE TABLE PRODUCT (
                         ID_PRODUCT    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         PRODUCT_CODE  VARCHAR2(30) NOT NULL UNIQUE,
                         NAME          VARCHAR2(100) NOT NULL,
                         UNIT_PRICE    NUMBER(15,2) NOT NULL
);

CREATE TABLE FEEDSTOCK (
                           ID_FEEDSTOCK     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           FEEDSTOCK_CODE   VARCHAR2(30) NOT NULL UNIQUE,
                           NAME             VARCHAR2(100) NOT NULL,
                           STOCK            NUMBER(18,6) DEFAULT 0 NOT NULL,
                           UNIT_OF_MEASURE  VARCHAR2(4) NOT NULL
);

CREATE TABLE PRODUCT_FEEDSTOCK (
                                   ID_PRODUCT    NUMBER NOT NULL,
                                   ID_FEEDSTOCK  NUMBER NOT NULL,
                                   QUANTITY      NUMBER(18,6) NOT NULL,

                                   CONSTRAINT PK_PRODUCT_FEEDSTOCK PRIMARY KEY (ID_PRODUCT, ID_FEEDSTOCK),

                                   CONSTRAINT FK_PF_PRODUCT
                                       FOREIGN KEY (ID_PRODUCT)
                                           REFERENCES PRODUCT(ID_PRODUCT)
                                           ON DELETE CASCADE,

                                   CONSTRAINT FK_PF_FEEDSTOCK
                                       FOREIGN KEY (ID_FEEDSTOCK)
                                           REFERENCES FEEDSTOCK(ID_FEEDSTOCK)
);

CREATE INDEX IX_PF_ID_FEEDSTOCK ON PRODUCT_FEEDSTOCK (ID_FEEDSTOCK);